### ISSUE TITLE
[RS2] Cannot query SeValidateImageData offset 

### ISSUE THREAD

**Issue by univert** [hfiref0x/UPGDSED#7]
```
Patch: Windows Version: 10.0.15063, LegacyBIOS

Patch: Symbol dlls extracted successfully.
Patch: Dbghelp initialized.
Patch: Copy files to %TEMP%
Patch: Copy success
Patch: Scanning ntoskrnl for patterns


Patch: Cannot query SeValidateImageData offset: Cannot complete this function.

Patch: Cannot locate patch offsets for ntoskrnl.
```

**Comment by hfiref0x** [comment]
Likely symbols have not yet released to your ntoskrnl.exe version after another cumulative patch.

**Comment by univert** [comment]
Strange. This is on a freshly installed RS2. Or does the symbols(pdb) need to be present in order for it to work?

**Comment by univert** [comment]
Got it working. It seem the target RS2 must have access to Microsoft symbol server in order for the tool to work.

**Comment by hfiref0x** [comment]
Yes. Perhaps this need to be highlighted somewhere in readme.

**Comment by LTFear** [comment]
A community of around 1000+ people are having to disable PatchGuard and this issue is somewhat common as even I'm experiencing it myself, what is the easiest way to fix this?

**Comment by Fyyre** [comment]
If you refer to the symbols not being available of Microsoft's public symbol server ... the only solution within the scope of the UPGDSED project is to wait until the symbols come available.

**Comment by LTFear** [comment]
So, what exactly causes the core issue, is it because I'm completely updated on my system, therefore symbols outdated? or

And how would I go about deleting the initial Patch Guard? Not sure what  < patch guard disable entry id >

**Comment by hfiref0x** [comment]
Microsoft didn't release symbols simultaneously with patch release. I don't know what the point of this simple because in case of bugs MS won't get appreciate comprehensive feedback without symbols. So it is their sluggishness.

Boot options managed by bcdedit. If you want to remove entry refer to bcdedit /delete help. E.g. https://social.technet.microsoft.com/Forums/windows/en-US/25e76f2f-2198-4068-ae3c-ebae94d16b31/how-can-i-delete-this-entry-in-bcdeditexe

**Comment by LTFear** [comment]
It seems the reason I got this error was because of the path "patch.exe" was located

I ran it on my Desktop and kept getting that error, I ran it from my Downloads where I had another copy from multiple downloads and it worked entirely, I just relaunched and booted into Patch Guard Disabled

Maybe add that in? Not sure why it being on the Desktop would cause this issue, because there are no major symbols in the directory

**Comment by hfiref0x** [comment]
Can you show exact error?

**Comment by LTFear** [comment]
I only have an image

![patch_2017-09-02_11-45-54](https://user-images.githubusercontent.com/30508115/29997101-cf102d6a-8fd8-11e7-8807-4083d51e871c.png)

**Comment by hfiref0x** [comment]
Can you reproduce it? With starting from desktop?

The reason why I ask is assumption that MS released symbols while we were talking here.

**Comment by hfiref0x** [comment]
Cannot reproduce. However the possible problem here is permissions set to desktop folder. During work patch.exe creates subdirectory named "Symbols" in the current process directory. Patch uses this "Symbols" dir as symbols storage during work. Maybe we will consider reviewing this part of the program in future updates.

![123](https://user-images.githubusercontent.com/10708977/30247420-79d44a4a-963e-11e7-9751-f8c56356a2e9.png)

**Comment by hfiref0x** [comment]
Test version, https://github.com/hfiref0x/UPGDSED/blob/dev/bin/patch.exe
Instead of current process directory it will use %temp% to store symbols.

If it still gives you the above error:
1) make sure you dont have any software/permissions blocking write to %temp%
2) make sure you unblocked patch.exe after downloading
3) symbols must be available for your version of system files

**Comment by dontbugmelol** [comment]
Thank you for this. @hfiref0x
